CI for docker release

diff --git a/.github/workflows/release-docker.yml b/.github/workflows/release-docker.yml
--- a/.github/workflows/release-docker.yml
+++ b/.github/workflows/release-docker.yml
@@ -13,19 +13,30 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v4
       
+    - name: Setup BRANCH_VERSION
+      run: |
+        BRANCH_VERSION=$(echo "${{ github.ref_name }}" | sed 's|\(v[0-9]\.[0-9]\).*|\1|')
+        if ! echo "$BRANCH_VERSION" | grep -q "v[0-9]\.[0-9]"; then
+          echo "Error: Invalid version format. Expected format is vX.Y"
+          exit 1
+        fi
+        echo "BRANCH_VERSION=${BRANCH_VERSION}" >> $GITHUB_ENV
+
+    - name: Build Docker image
+      run: ./build.sh docker
+
     - name: Log in to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Build Docker image
-      run: ./build.sh docker
-
     - name: Push Docker image
       run: |
         docker tag portsentry:unstable portsentry/portsentry:latest
         docker tag portsentry:unstable portsentry/portsentry:${{ github.ref_name }}
+        docker tag portsentry:unstable portsentry/portsentry:${{ env.BRANCH_VERSION }}
         docker push portsentry/portsentry:latest
         docker push portsentry/portsentry:${{ github.ref_name }}
+        docker push portsentry/portsentry:${{ env.BRANCH_VERSION }}
 
